"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OK = 200;
exports.CREATED = 201;
exports.NO_CONTENT = 204;
exports.MOVED_PERMANENTLY = 301;
exports.BAD_REQUEST = 400;
exports.UNAUTHORIZED = 401;
exports.NOT_FOUND = 404;
exports.FORBIDDEN = 403;
exports.CONFLICT = 409;
exports.INTERNAL_SERVER_ERROR = 500;
